### ISSUE TITLE
Can this system support Chinese input?

### ISSUE THREAD

**Issue by tuyunbin** [Yingda-Guo/Sentimenal-Analysis#1]
Hi, Dr. Guo, thanks for your good system. Can this system support Chinese input?

**Comment by Yingda-Guo** [comment]
Hi Yunbin, that simple shiny app uses TextBlob which only supports for English text. However, I found the NLPIR has Chinese sentiment analysis and has a python package (https://github.com/NLPIR-team/nlpir-python)
